/**
 * jDiet - tiny framework for javascript nerds
 * @author Tom Flidr | tomflidr(at)gmail(dot)com
 * @version 1.9
 * @date 2015-04-14
 */
var jDiet=(function(doc,win,jDiet,jdw){jDiet=function(){var a=[].slice.apply(arguments);if(typeof jDiet.local.makeResult=="undefined"){this.length=0;return this}else if(typeof a[0]=="string"&&a[0].substr(0,1)=="<"&&a[0].substr(a[0].length-1,1)==">")return jDiet.local.createElm.apply(this,a);else if(typeof a[0]=="string"&&(typeof a[1]=="undefined"||typeof a[1]=="string"||typeof a[1]=="object"))jDiet.local.makeResult.apply(this,jDiet.local.getElementsBySelectorsAndContext.apply(jDiet.local,a));else if(typeof a[0]=="object"&&(typeof a[0].nodeType!=
"undefined"||typeof a[0].frames!="undefined"))jDiet.local.makeResult.call(this,[a[0]],a[0])};jDiet.DEBUG=false;jDiet.local={};jDiet.browser={version:0};jDiet.toString=function(){return"[jDiet]"};
jDiet.local.browserRecognizers={msie:{bmatch:/MSIE [0-9]|Trident\/[0-9]/g,vmatch:function(a){return/MSIE [0-9]/g.test(a)?a.replace(/(.*)MSIE ([0-9\.]*);(.*)/g,"$2"):a.replace(/(.*)rv:([0-9\.]*)(.*)/g,"$2")}},chrome:{bmatch:/Chrome/g,vmatch:[/(.*)Chrome\/(.*) Safari(.*)/g,"$2"]},safari:{bmatch:/Safari/g,vmatch:[/(.*)Version\/(.*) Safari(.*)/g,"$2"]},opera:{bmatch:/Opera/g,vmatch:function(a){return a.indexOf("Version")>-1?a.replace(/(.*)Version\/(.*)scope/g,"$2"):a.replace(/(.*)Opera.([0-9])/g,"$2").replace(/([0-9]*) (.*)/g,
"$1")}},firefox:{bmatch:/Firefox\//g,vmatch:function(a){a=a.replace(/(.*) Firefox\/(.*)/g,"$2");if(a.indexOf(" ")>-1)a=a.substr(0,a.indexOf(" "));return a}},gecko:{bmatch:/Gecko\//g,vmatch:[/(.*); rv:(.*)\)(.*)/g,"$2"]},other:{bmatch:/(.*)/g,vmatch:[/[^0-9\.]/g,""]}};
jDiet.local.recognizeBrowser=function(){var a=navigator.userAgent,b;for(b in this.browserRecognizers)jDiet.browser[b]=0;for(b in this.browserRecognizers){var c=this.browserRecognizers[b];if(c.bmatch.test(a)){jDiet.browser[b]=1;jDiet.browser.name=b;b="";b=typeof c.vmatch=="function"?c.vmatch(a):a.replace(c.vmatch[0],c.vmatch[1]);jDiet.browser.version=parseFloat(b);break}}if(a.indexOf("Gecko/")>-1){jDiet.browser.gecko=1;if(/rv\:[0-9]{1}/gi.test(a))jDiet.browser.geckoVersion=parseFloat(a.substr(a.indexOf("rv:")+
3))}};jDiet.local.recognizeBrowser();jDiet.prototype.eachCall=function(a){return this.each.call(this,a)};jDiet.prototype.each=function(){for(var a=[].slice.apply(arguments),b=a[0],c=typeof this.length=="number"?this.length:1,d=0;d<c;d+=1)if(typeof this[d]!="undefined"){a[0]=parseInt(d,10);if(b.apply(this[d],a)===false)break}return this};jDiet.prototype.toString=function(){return jDiet.toString()};jDiet.fn=jDiet.prototype;
jDiet.trim=function(a,b){var c,d=0,e=0;a+="";if(b){b+="";c=b.replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g,"$1")}else c=" \n\r\t\u000c\u000b\u00a0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000";d=a.length;for(e=0;e<d;e++)if(c.indexOf(a.charAt(e))===-1){a=a.substring(e);break}d=a.length;for(e=d-1;e>=0;e--)if(c.indexOf(a.charAt(e))===-1){a=a.substring(0,e+1);break}return c.indexOf(a.charAt(0))===-1?a:""};
jDiet.local.createElm=function(a,b){var c=a.substr(1,a.length-2);c=new jDiet(doc.createElement(c));if(typeof b!="undefined"){b.attrs&&c.setAttr(b.attrs);b.css&&c.css(b.css);if(b.elms)for(var d=0,e=b.elms.length;d<e;d+=1){var f=b.elms[d];f=arguments.callee(f[0],f[1]);c.append(f[0])}else if(b.html)c[0].innerHTML=b.html}return c};jDiet.local.makeResult=function(a,b,c){for(var d=0,e=a.length;d<e;d+=1)this[d]=a[d];this.length=e;this.context=b||doc;this.selector=c?c:"this";return this};
jDiet.local.getElementsBySelectorsAndContext=function(a,b){b=b||doc;var c=[],d=[],e=[],f=[];d="";for(var g=a.replace(/,[\s]*/gi,",").split(","),i=0,h=g.length;i<h;i+=1){d=jDiet.trim(g[i]);if(d.indexOf(" ")>-1){f=d.split(" ");e=[this.getElementsBySelectorAndContext(f[0],b)];for(var k=1;k<f.length;k+=1){d=e[k-1];e[k]=[];for(var l=0;l<d.length;l+=1)e[k]=e[k].concat(jDiet.local.catchChildNodesBySelector(d[l],jDiet.local.parseSelector(f[k])))}c=c.concat(e[e.length-1])}else{d=this.getElementsBySelectorAndContext(d,
b);c=c.concat(d)}}return[c,b,a]};
jDiet.local.getElementsBySelectorAndContext=function(a,b){var c=[],d=[];if(a.indexOf("#")>-1&&a.indexOf("#")+1<a.length){var e=b.getElementById(a.substr(a.indexOf("#")+1));if(e!==null)c=[e]}else c=a.indexOf(".")>-1&&a.indexOf(".")+1<a.length?jDiet.browser.msie&&jDiet.browser.version<8||typeof b.querySelectorAll=="undefined"?this.getElementsBySelectorAndContextInOldIE(a,b):b.querySelectorAll(a):b.getElementsByTagName(a);if(jDiet.browser.msie)for(var f in c)c[f]!==null&&typeof c[f]=="object"&&typeof c[f].nodeName==
"string"&&d.push(c[f]);else d=[].slice.apply(c);return d};jDiet.local.getElementsBySelectorAndContextInOldIE=function(a,b){var c=[],d="",e=0;if(a.indexOf("#")>-1){e=a.indexOf("#");d=String(a.substr(0,e)).toLowerCase();a=a.substr(e+1)}if(a.indexOf(".")>-1){e=a.indexOf(".");d=String(a.substr(0,e)).toLowerCase();a=a.substr(e+1)}d||(d="*");d=b.getElementsByTagName(d);e=" "+a+" ";for(var f in d)String(" "+d[f].className+" ").indexOf(e)!==-1&&c.push(d[f]);return c};
jDiet.local.catchElementBySelector=function(a,b){var c=[0,0,0];if(b===false)return a!==null&&typeof a=="object"&&String(a.nodeName).toLowerCase()!=="#text"?true:false;else{if(b.nodeName)if(String(a.nodeName).toLowerCase()==b.nodeName)c[0]=1;if(b.id)if(a.id==b.id)c[1]=1;if(b.className&&typeof a.className=="string"){var d=" "+a.className.replace(/\t/," ").replace(/\s\s/," ")+" ";if(RegExp(" "+b.className+" ","gi").test(d))c[2]=1}return b.nodeName&&!c[0]||b.id&&!c[1]||b.className&&!c[2]?false:true}};
jDiet.local.parseSelector=function(a){if(typeof a=="undefined")return false;var b=[],c={nodeName:"",id:"",className:""};if(a.indexOf("#")>0){b=a.split("#");c.nodeName=b[0].toLowerCase();c.id=b[1]}else if(a.indexOf(".")>0){b=a.split(".");c.nodeName=b[0].toLowerCase();c.className=b[1]}else if(a.indexOf("#")===0){b=a.split("#");c.id=b[1]}else if(a.indexOf(".")===0){b=a.split(".");c.className=b[1]}else c.nodeName=a.toLowerCase();return c};
jDiet.local.catchChildNodesBySelector=function(a,b){for(var c=[],d,e=0;e<a.childNodes.length;e+=1){d=a.childNodes[e];jDiet.local.catchElementBySelector(d,b)&&c.push(d)}return c};jDiet.local.cleanClassName=function(a){a=a.replace(/\s{2,}/g," ");return jDiet.trim(a)};
jDiet.prototype.children=function(a){var b=jDiet.local.parseSelector(a),c=[];this.eachCall(function(){c=c.concat(jDiet.local.catchChildNodesBySelector(this,b))});var d=this.selector?this.selector:"this";return jDiet.local.makeResult.call(new jDiet,c,this.context,d+" > "+(a?a:""))};
jDiet.prototype.parent=function(){var a=[];this.eachCall(function(){typeof this.parentNode!="undefined"&&a.push(this.parentNode)});var b=this.selector?this.selector:"this";return jDiet.local.makeResult.call(new jDiet,a,this.context,b+" < parent")};
jDiet.prototype.prepend=function(a){var b=[],c=this.length===1?1:0;this.eachCall(function(){var d=c?a:a.cloneNode(true);jDiet.browser.msie&&jDiet.browser.version<9?b.push(this.insertAdjacentElement("afterBegin",d)):b.push(this.insertBefore(d,this.firstChild))});return jDiet.local.makeResult.call(new jDiet,b,this.context?this.context:undefined)};
jDiet.prototype.append=function(a){var b=[],c=this.length===1?1:0;this.eachCall(function(){var d=c?a:a.cloneNode(true);jDiet.browser.msie&&jDiet.browser.version<9?b.push(this.insertAdjacentElement("beforeEnd",d)):b.push(this.appendChild(d))});return jDiet.local.makeResult.call(new jDiet,b,this.context?this.context:undefined)};
jDiet.prototype.addClass=function(a){this.eachCall(function(){for(var b=jDiet.local.cleanClassName(this.className),c=b.split(" "),d=false,e=0,f=c.length;e<f;e+=1)if(c[e]==a){d=true;break}d||(this.className=b+" "+a)});return this};jDiet.prototype.removeClass=function(a){var b=RegExp(" "+a+" ","gi");this.eachCall(function(){var c=" "+jDiet.local.cleanClassName(this.className)+" ";c=c.replace(b," ");this.className=jDiet.local.cleanClassName(c)});return this};
jDiet.prototype.hasClass=function(a){var b=false;this.eachCall(function(){if((" "+jDiet.local.cleanClassName(this.className)+" ").indexOf(" "+a+" ")>-1)b=true;return false});return b};jDiet.prototype.setAttr=function(a){this.eachCall(function(){for(var b in a)if(b=="class")this.className=String(this.className+" "+a[b]).replace(/\s\s/gm," ");else this.setAttribute(b,a[b])});return this};
jDiet.prototype.getAttr=function(a){a=a.toLowerCase();var b=null,c=jDiet.browser,d=c.msie;c=c.version;var e=Boolean(a=="style");if(e&&d&&c<8)this.eachCall(function(){var f=String(this.outerHTML),g=f.indexOf(">");if(g>-1){f=f.substr(0,g+1).toLowerCase().replace(/\t\r\n/g,"").replace(/(\s)*=/g,"=").replace(/=(\s)*"/g,'="').replace(/=(\s)*'/g,"='").replace(/[']/g,'"');g=f.indexOf('style="');var i=f.indexOf('"',Math.max(g,0));g>-1&&i>-1&&jDiet.trim(f.substring(g+7,i))}else return false});else{this.eachCall(function(){var f=
this.getAttribute(a);if(typeof f=="string"){b=f;return false}});if(e&&d&&c==8&&typeof b=="string"&&b.length>0)b=b.toLowerCase()+";"}return b};jDiet.prototype.removeAttr=function(a){this.eachCall(function(){this.removeAttribute(a)});return this};
jDiet.prototype.val=function(){var a=this.context.ownerDocument||doc,b="";this.eachCall(function(){var c,d=true,e="innerHTML",f=String(this.nodeName).toLowerCase();if(f=="input"||f=="select"||f=="textarea"){e="value";if(f=="input"){f=String(this.getAttribute("type")).toLowerCase();if(f=="checkbox"){d=false;if(this.checked){c=this[e];if(c=="")c="on"}}else if(f=="radio"){d=false;c="";f=a.getElementsByName(this.name);for(var g in f)if(String(f[g].nodeName).toLowerCase()=="input"&&f[g].getAttribute("type")==
"radio")if(f[g].checked){c=f[g][e];break}}}}if(d)c=this[e];if(typeof c=="string"){b=c;return false}});return b};jDiet.prototype.checked=function(a){var b=typeof a=="undefined",c;this.eachCall(function(){if(b){c=Boolean(this.checked);return false}else this.checked=Boolean(a)});return b?c:this};
try{doc.write=function(a){return function(b){if(jDiet.domReady.loaded){b=new jDiet("<div>",{html:b});return(new jDiet(doc.body)).append(b[0].firstChild)[0]}else return jDiet.browser.msie&&jDiet.browser.version<8?a(b):a.call(this,b)}}(doc.write);doc.writeln=function(a){return function(b){if(jDiet.domReady.loaded){b=new jDiet("<div>",{html:b});return(new jDiet(doc.body)).append(b[0])[0]}else return jDiet.browser.msie&&jDiet.browser.version<8?a(b):a.call(this,b)}}(doc.writeln)}catch(e$$6){}
jDiet.domReady={add:function(a){if(jDiet.domReady.loaded)return a();var b=jDiet.domReady.observers;if(!b)b=jDiet.domReady.observers=[];b[b.length]=a;if(!jDiet.domReady.callback){jDiet.domReady.callback=function(){if(!jDiet.domReady.loaded){jDiet.domReady.loaded=true;if(jDiet.domReady.timer){clearInterval(jDiet.domReady.timer);jDiet.domReady.timer=null}for(var d=jDiet.domReady.observers,e=0,f=d.length;e<f;e++){var g=d[e];d[e]=null;g()}jDiet.domReady.callback=jDiet.domReady.observers=null}};b=!!(win.attachEvent&&
!win.opera);var c=navigator.userAgent.indexOf("AppleWebKit/")>-1;if(doc.readyState&&c)jDiet.domReady.timer=setInterval(function(){var d=doc.readyState;if(d=="loaded"||d=="complete")jDiet.domReady.callback()},50);else if(doc.readyState&&b)doc.write('<script type="text/javascript" defer="defer" src="'+(win.location.protocol=="https:"?"://0":"javascript:void(0)")+'" onreadystatechange="if(this.readyState==\'complete\')jDiet.domReady.callback();"><\/script>');else if(win.addEventListener){doc.addEventListener("DOMContentLoaded",
jDiet.domReady.callback,false);win.addEventListener("load",jDiet.domReady.callback,false)}else if(win.attachEvent)win.attachEvent("onload",jDiet.domReady.callback);else{a=win.onload;win.onload=function(){jDiet.domReady.callback();a&&a()}}}}};jDiet.domReady.add(function(){jDiet.domReady.loaded=true});jDiet.local.elementsVsHandlers=[];jDiet.local.getEventKey=function(a,b,c){return"{FNKEY::el_"+(a===win?"theWindow":a===doc?"theDocument":a.uniqueID)+"::evt_"+b+"::fn_"+c.toString().replace(/\s/g,"")+"}"};
jDiet.local.getMousePositions=function(a){var b=[];b=[];b=doc.documentElement;var c=doc.body;if(jDiet.browser.msie){b=b&&b.scrollTop?[b.scrollLeft,b.scrollTop]:[c.scrollLeft,c.scrollTop];b=[a.clientX+b[0],a.clientY+b[1]]}else b=[a.pageX,a.pageY];return b};
jDiet.local.bindEvent=function(a,b,c,d){var e=this;if(jDiet.browser.msie&&typeof a.attachEvent!="undefined"){var f=false,g={preventDefault:function(){f=true}},i=function(h){h=h||win.event;for(var k in h)g[k]=h[k];g.srcElement=a;h=e.getMousePositions(h);g.pageX=h[0];g.pageY=h[1];c.call(a,g);if(f)return false;return true};d=e.getEventKey(a,b,c);e.elementsVsHandlers[d]=i;a.attachEvent("on"+b,i);win.attachEvent("onunload",function(){a.detachEvent("on"+b,i)})}else typeof a.addEventListener=="function"&&
a.addEventListener(b,c,d)};jDiet.prototype.bind=function(a,b,c){if(a&&b){var d=a.replace(/\s/g,"").split(",");this.eachCall(function(){if(typeof this=="object")for(var e=0,f=d.length;e<f;e+=1){var g=d[e];this.nodeName=="#document"&&g=="ready"?jDiet.domReady.add(b):jDiet.local.bindEvent(this,g,b,c)}});return this}};
jDiet.prototype.unbind=function(a,b,c){if(a&&b){var d=a.replace(/\s/g,"").split(",");this.eachCall(function(){if(typeof this=="object")for(var e=0,f=d.length;e<f;e+=1){var g=d[e];if(jDiet.browser.msie&&jDiet.browser.version<9){var i=jDiet.local.getEventKey(this,g,b),h=jDiet.local.elementsVsHandlers[i];if(typeof h!="undefined"){this.detachEvent("on"+g,h);delete jDiet.local.elementsVsHandlers[i]}}else this.removeEventListener(g,b,c)}});return this}};
Function.prototype.bind||(Function.prototype.bind=function(a){if(typeof this!=="function")throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a||win,b.concat(Array.prototype.slice.call(arguments)))};d.prototype=this.prototype;e.prototype=new d;return e});jDiet.FRAMERATE=20;
jDiet.local.displayPropertiesNodeNames=["table","table-row","table-cell","inline"];jDiet.local.displayPropertiesNodeNameIndexes={table:0,tr:1,th:2,td:2,span:3,i:3,b:3,strong:3,em:3,img:3,br:3,input:3,abbr:3,acronym:3,u:3,a:3};new function(){if(jDiet.browser.msie&&jDiet.browser.version<8){jDiet.local.displayPropertiesNodeNames[1]="";jDiet.local.displayPropertiesNodeNames[2]=""}};
jDiet.local.styleOne=function(a,b){if(jDiet.DEBUG)try{jDiet.local.styleOneElm(a,b)}catch(c){for(var d=arguments.callee.caller;;)if(d.toString()=="[jDiet]"){d=d.caller.caller;break}else d=d.caller;jDiet.DEBUG("Wrong args called from:\r\n"+d.toString())}else jDiet.local.styleOneElm(a,b)};jDiet.local.styleOneElm=function(a,b){for(var c in b)a.style[c]=(c=="width"||c=="height"||c=="top"||c=="bottom"||c=="left"||c=="right")&&/^[0-9\-\.]*$/g.test(b[c])?b[c]+"px":b[c]};
jDiet.prototype.fx={easing:{easeIn:function(a,b,c,d,e){return this.makeSinusEase({begin:0,finall:Math.PI/2,range:1},b,c,d,e)},easeOut:function(a,b,c,d,e){return this.makeSinusEase({begin:-(Math.PI/2),finall:0,range:1},b,c,d,e)},easeInOut:function(a,b,c,d,e){return this.makeSinusEase({begin:-(Math.PI/2),finall:Math.PI/2,range:2},b,c,d,e)},easeOutBackIn:function(a,b,c,d,e){this.easing.easeOutBackIn.sinEndMarginWatcher=this.easing.easeOutBackIn.sinEndMarginWatcher||[0,0];return this.makeSinusEase({begin:-(Math.PI/
2),finall:Math.PI/2+0.75,range:jDiet.browser.msie?1.8:1.9},b,c,d,e)},backOutEaseIn:function(a,b,c,d,e){return this.makeSinusEase({begin:-(Math.PI/2)-0.75,finall:Math.PI/2,range:1.7},b,c,d,e)},backInOut:function(a,b,c,d,e){this.easing.backInOut.sinEndMarginWatcher=this.easing.backInOut.sinEndMarginWatcher||[0,0];return this.makeSinusEase({begin:-(Math.PI/2)-0.75,finall:Math.PI/2+0.75,range:1.5},b,c,d,e)},linear:function(a,b,c,d,e){return c+(d-c)*(b/e)}},getEasingFn:function(a){a=this.easing[a?a:"linear"];
if(a.sinBeginMarginWatcher!="undefined")a.sinBeginMarginWatcher=[0,0];if(a.sinEndMarginWatcher!="undefined")a.sinEndMarginWatcher=[0,0];return a},completeBeginAnimateProps:function(a,b){var c={},d={width:"offsetWidth",height:"offsetHeight",left:"offsetLeft",top:"offsetTop"},e;for(e in d)if(typeof b[e]!="undefined")c[e]=a[d[e]];return[c,b]},makeSinusEase:function(a,b,c,d,e){var f=d-c,g=Math.sin(a.begin+b/e*(a.finall-a.begin)),i=Math.sin(a.finall)*-1+1,h=Math.sin(a.begin);h=h<0?h*-1:0;g+=Math.max(i,
h);g/=a.range;i=["sinEndMarginWatcher"];for(var k in i){h=i[k];if(typeof arguments.callee.caller!="undefined"&&typeof arguments.callee.caller[h]!="undefined"){var l=arguments.callee.caller[h];if(l[0]==1)if(k===0&&g<l[1])g=1;else l=[1,g];else if(k===0&&g>1)l=[1,g];arguments.callee.caller[h]=l}}return c+g*f},animateOne:function(a,b,c,d,e){var f=this,g=(new Date).getTime(),i=this.getEasingFn(d);d=this.completeBeginAnimateProps(a,b);var h=d[0];b=d[1];var k=function(){var l=(new Date).getTime()-g;if(l<
c){var m={},n;for(n in b)m[n]=i.apply(f,[null,l,h[n],b[n],c]);jDiet.local.styleOne(a,m);a.jDietFxId=setTimeout(k,1E3/jDiet.FRAMERATE)}else{jDiet.local.styleOne(a,b);e&&e()}};a.jDietFxId=setTimeout(k,1E3/jDiet.FRAMERATE)}};jDiet.prototype.animate=function(a,b,c,d){c=c?c:"linear";var e=this;this.eachCall(function(){e.fx.animateOne(this,a,b,c,d)});return this};jDiet.prototype.stop=function(){this.eachCall(function(){clearTimeout(this.jDietFxId)});return this};
jDiet.prototype.hide=function(){this.eachCall(function(){this.style.display="none"});return this};jDiet.prototype.show=function(){var a="",b="";this.eachCall(function(){a=String(this.nodeName).toLowerCase();b=typeof jDiet.local.displayPropertiesNodeNameIndexes[a]!="undefined"?jDiet.local.displayPropertiesNodeNames[jDiet.local.displayPropertiesNodeNameIndexes[a]]:"block";this.style.display=b});return this};jDiet.prototype.setCss=function(a){this.eachCall(function(){jDiet.local.styleOne(this,a)});return this};
jDiet.prototype.getCss=function(a){var b="",c=this.context.ownerDocument||doc;this.eachCall(function(){var d;if(c.defaultView&&c.defaultView.getComputedStyle)d=c.defaultView.getComputedStyle(this,"").getPropertyValue(a);else if(this.currentStyle){a=a.replace(/\-(\w)/g,function(e,f){return f.toUpperCase()});d=this.currentStyle[a]}if(d!==null){b=d;return false}return true});return b};
jDiet.prototype.getCssFloat=function(a){var b=false,c=0;a=this.getCss(a);a=a.replace(/[^0-9\.]/g,"");if(a.length&&a!=="."){b=true;c=parseFloat(a)}return[b,c]};jDiet.prototype.offset=function(){var a={left:0,top:0};if(typeof this[0]!="undefined"){var b=this[0];if(typeof b.x!="undefined"&&typeof b.y!="undefined"){a.left=b.x;a.top=b.y}else for(;;){a.left+=b.offsetLeft;a.top+=b.offsetTop;if(b.offsetParent)b=b.offsetParent;else break}}return a};
jDiet.ajax=function(a){if(!a)return"mandatory params: \n\t'uri' (String)\noptional params: \n\t'async' (Boolean), \n\t'data' (Mixed), \n\t'method' (Sring), \n\t'success' (Function), \n\t'error' (Function), \n\t'headers' (Object), \n\t'cache' (Boolean)";var b="";a.async=a.async||true;a.method=String(a.method).toUpperCase()||"GET";a.headers=a.headers||{"Content-Type":"application/x-www-form-urlencoded"};if(a.data&&a.data!==null&&typeof a.data=="object"){var c=0,d="",e;for(e in a.data){d=typeof a.data[e]!==
null&&typeof a.data[e]=="object"?JSON.stringify(a.data[e]):String(a.data[e]);b+=(c>0?"&":"")+e+"="+d;c+=1}}if(a.uri){c=a.uri;d=c.indexOf("?")>-1?"&":"?";if(c.charAt(c.length-1)=="&")c=c.substr(1,c.length-2);if(a.method=="GET"&&b.length>0)c+=d+b;if(!a.cache){d=c.indexOf("?")>-1?"&":"?";c+=d+String("_="+Math.random()+Math.random()+Math.random()).replace(/\./g,"")}var f=this.local.getXhrObject();f.open(a.method,c,a.async);c=a.headers;if(typeof c["X-Requested-With"]=="undefined")c["X-Requested-With"]=
"XMLHttpRequest";for(var g in c)String(c[g]).length>0&&f.setRequestHeader(g,c[g]);f.onreadystatechange=function(){if(f.readyState==4){var i=function(){};if(f.status==200){if(a.success)i=a.success}else if(a.error)i=a.error;i(f.responseText,f.status,f,f.getAllResponseHeaders())}};b&&a.method=="POST"?f.send(b):f.send()}};jDiet.local.getXhrObject=function(){};
jDiet.local.setUpXhrObject=function(){for(var a=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new ActiveXObject("Msxml2.XMLHTTP")}],b,c=0;c<a.length;c++){try{b=a[c]()}catch(d){}if(b)break}this.getXhrObject=a[c]};jDiet.local.setUpXhrObject();
this.JSON||(JSON=function(){function a(d){return d<10?"0"+d:d}function b(d,e){var f,g,i,h;f=/["\\\x00-\x1f\x7f-\x9f]/g;var k;switch(typeof d){case "string":return f.test(d)?'"'+d.replace(f,function(l){var m=c[l];if(m)return m;m=l.charCodeAt();return"\\u00"+Math.floor(m/16).toString(16)+(m%16).toString(16)})+'"':'"'+d+'"';case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";if(typeof d.toJSON==="function")return b(d.toJSON());
f=[];if(typeof d.length==="number"&&!d.propertyIsEnumerable("length")){h=d.length;for(g=0;g<h;g+=1)f.push(b(d[g],e)||"null");return"["+f.join(",")+"]"}if(e){h=e.length;for(g=0;g<h;g+=1){i=e[g];if(typeof i==="string")(k=b(d[i],e))&&f.push(b(i)+":"+k)}}else for(i in d)if(typeof i==="string")(k=b(d[i],e))&&f.push(b(i)+":"+k);return"{"+f.join(",")+"}"}}Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+
":"+a(this.getUTCSeconds())+"Z"};var c={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:b,parse:function(d,e){function f(i,h){var k,l;if(h&&typeof h==="object")for(k in h)if(Object.prototype.hasOwnProperty.apply(h,[k])){l=f(k,h[k]);if(l!==undefined)h[k]=l}return e(i,h)}var g;if(/^[\],:{}\s]*$/.test(d.replace(/\\./g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){g=eval("("+
d+")");return typeof e==="function"?f("",g):g}throw new SyntaxError("parseJSON");}}}());jDiet.isset=function(a,b){var c=true,d=[a],e=0;if(typeof b=="string")var f=b.split(".");this.test=this.test||function(h){return typeof h!="undefined"&&h!==null?true:false};if(this.test(a)){if(typeof b!="string")return this.test(a[b]);for(var g=0,i=f.length;g<i;g+=1){d[e+1]=d[e][f[g]];this.test(d[e+1])||(c=false);e+=1}}else c=false;return c};
jDiet.typeOf=function(a){return String(Object.prototype.toString.apply(a)).toLowerCase().replace("[object ","").replace("]","")};jDiet.clone=function(a){return jDiet.local.objectClone(a)};jDiet.local.objectClone=function(a){var b;if(jDiet.typeOf(a)=="array")b=jDiet.local.arrayClone(a);else if(typeof a=="object")if(a){b={};for(var c in a){var d=a[c];b[c]=typeof d=="object"?arguments.callee(d):d}}else b=null;else b=a;return b};
jDiet.local.arrayClone=function(a){var b;if(jDiet.typeOf(a)=="object")b=jDiet.local.objectClone(a);else if(typeof a=="object"){b=[];for(var c in a){var d=a[c];b[c]=typeof d=="object"?d?arguments.callee(d):null:d}}else b=a;return b};jDiet.prototype.attr=function(){var a=[].slice.apply(arguments);if(typeof a[0]=="object"&&a.length===1)return this.setAttr(a[0]);else if(typeof a[0]=="string"&&a.length===2){var b={};b[a[0]]=a[1];return this.setAttr(b)}else if(typeof a[0]=="string")return this.getAttr(a[0])};
jDiet.prototype.css=function(){var a=[].slice.apply(arguments);if(typeof a[0]=="object"&&a.length===1)return this.setCss(a[0]);else if(typeof a[0]=="string"&&a.length===2){var b={};b[a[0]]=a[1];return this.setCss(b)}else if(typeof a[0]=="string")return this.getCss(a[0])};jDiet.prototype.ready=function(a){if(a){this.eachCall(function(){typeof this=="object"&&this.nodeName=="#document"&&jDiet.domReady.add(a)});return this}};jdw=function(a,b){return new jDiet(a,b)};for(var j in jDiet)jdw[j]=jDiet[j];
return jdw})(document,window,function(){});